name: Bug Report
description: Found a bug? Use this template!
labels: 'bug'
assignees: 'amsam0'
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Please add a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To reproduce
    description: Please add *descriptive* steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: Please add a clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, please add screenshots to help explain your problem.
- type: textarea
  attributes:
    label: Logs
    description: |
      To be able to debug your problem, we need your server logs. To obtain them:
      1. Set `debug_level` to `3` (or `2` if there's too much spam) in the Simple Voice Chat Discord Bridge configuration file
      2. Restart your server or use `/dvc reloadconfig`
      3. **Reproduce the issue**
      4. Upload the server logs here (they can be found in `logs/latest.txt`; make sure they don't include any sensitive info such as IP addresses)
      
      We recommend using pastebin services such as https://mclo.gs/.
  validations:
    required: true
- type: input
  attributes:
    label: Minecraft version
  validations:
    required: true
- type: dropdown
  attributes:
    label: Loader/server software
    options: 
      - -- PLEASE SELECT --
      - Paper
      - Purpur
      - Fabric
      - Quilt
      - Other (PLEASE SPECIFY IN ADDITONAL CONTEXT)
  validations:
    required: true
- type: input
  attributes:
    label: Simple Voice Chat version
  validations:
    required: true
- type: input
  attributes:
    label: Simple Voice Chat Discord Bridge version
  validations:
    required: true
- type: checkboxes
  attributes:
    options:
      - label: Are you using offline mode?
        required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
