name: Build and publish stable release

on:
  push:
    branches:
      - main

jobs:
  natives:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-22.04
            triple: unknown-linux-gnu
            filename: libvoicechat_discord.so
            pre-install: sudo apt-get update -y #&& sudo apt-get install -y curl
            #container: debian:buster
          - os: windows-latest
            triple: pc-windows-gnu
            filename: voicechat_discord.dll

    runs-on: ${{ matrix.os }}
    #container:
    #  image: ${{ matrix.container }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre-package installation
        if: ${{ matrix.pre-install }}
        run: ${{ matrix.pre-install }}

      - name: Install packages
        if: ${{ matrix.install }}
        run: ${{ matrix.install }}

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-${{ matrix.triple }}

      - name: Build ${{ matrix.arch }}-${{ matrix.triple }}
        run: cargo build --target ${{ matrix.arch }}-${{ matrix.triple }} --release
        working-directory: core

      - name: Upload ${{ matrix.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.arch }}-${{ matrix.triple }}
          path: core/target/${{ matrix.arch }}-${{ matrix.triple }}/release/${{ matrix.filename }}
          if-no-files-found: error

  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    needs: [natives]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download linux-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x64/

      - name: Download windows-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-pc-windows-gnu
          path: core/src/main/resources/natives/windows-x64/

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
        continue-on-error: true

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Remove raw and shadow jars
        run: rm -f paper/build/libs/voicechat-discord-paper-*-raw.jar paper/build/libs/voicechat-discord-paper-*-shadow.jar

      - name: Upload final jar
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-final-jar
          path: paper/build/libs/voicechat-discord-paper-[0-9]*.jar
          if-no-files-found: error
